---
# defaults file for user_management

user_management_users: []

user_management_users_remove: []

user_management_default_shell: /bin/bash

user_management_create_home: true

user_management_remove_home: true

user_management_additional_groups: []